# Generated by Django 3.1.3 on 2020-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=10)),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('classes_conducted', models.CharField(max_length=30)),
                ('classes_attended', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('obtained_marks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('classes_conducted', models.CharField(max_length=30)),
                ('classes_attended', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('obtained_marks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('classes_conducted', models.CharField(max_length=30)),
                ('classes_attended', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('obtained_marks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('food', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('hello', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('classes_conducted', models.CharField(max_length=30)),
                ('classes_attended', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('obtained_marks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='physics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30)),
                ('classes_conducted', models.CharField(max_length=30)),
                ('classes_attended', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('obtained_marks', models.CharField(max_length=30)),
            ],
        ),
    ]
